### ISSUE TITLE
Missing spaces on summary page

### ISSUE THREAD

**Issue by llarall** [PamVanLonden/cognitive-styles#5]
There are spaces missing on the summary page. Example:
"ages,you are50% like Abi and50% like Tim"

When I run the code locally, this does not happen, so I'm not sure how to debug.

Maybe adding some "&nbsp;" entities would work?

**Comment by PamVanLonden** [comment]
I'll fix it in the morning. I know what to do.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: llarall ***@***.***>
Sent: Monday, September 30, 2024 4:57:15 PM
To: PamVanLonden/cognitive-styles ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PamVanLonden/cognitive-styles] Missing spaces on summary page (Issue #5)


[This email originated from outside of OSU. Use caution with links and attachments.]

There are spaces missing on the summary page. Example:
"ages,you are50% like Abi and50% like Tim"

When I run the code locally, this does not happen, so I'm not sure how to debug.

Maybe adding some " " entities would work?
