### ISSUE TITLE
Survey summary fails to download if fingerprinting protection is enabled

### ISSUE THREAD

**Issue by ArtofBugs** [PamVanLonden/cognitive-styles#6]
If fingerprinting protection is enabled, Pica will fail to resize the image [1], causing the download to fail silently. Fingerprinting protection can be disabled in the browser settings, but this may require the page to reload, losing all survey data.

[1] https://github.com/nodeca/pica/issues/229

**Comment by PamVanLonden** [comment]
Thank you! I've removed PICA in favor of other tools, which are in my new branch.

**Comment by cadilhac** [comment]
> Thank you! I've removed PICA in favor of other tools, which are in my new branch.

What tools please?
